version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8000"
       # - "443:443"
    volumes:
      # - ./eduz-app.com.crt:/etc/ssl/certs/eduz-app.com.crt
      # - ./eduz-app.com.key:/etc/ssl/private/eduz-app.com.key
      # - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
      # - ./default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
 
      - .:/var/www/html
      -  ./config_php/php.ini:/usr/local/etc/php/php.ini:ro
 
    # depends_on:
    #   - db
    environment:
      DB_HOST: 93.158.238.134
      DB_PORT: 1433
      DB_DATABASE: RhallaMobile
      DB_USERNAME: RhallaMo
      DB_PASSWORD: RhallaMo2024@_2024
      PHP_UPLOAD_MAX_FILESIZE: 40M  # Set the upload_max_filesize
      PHP_POST_MAX_SIZE: 40M  
 
    command: php artisan serve --host=0.0.0.0 --port=8000
  # db: RhallaMobile
  #   image: mariadb
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root@45588522
  #     MYSQL_DATABASE: rahala_prod
  #   volumes:
  #     - ./db_data:/var/lib/mysql


    # sql-server:
    #   image: microsoft/mssql-server-linux
    #   environment:
    #       SA_PASSWORD: "YourStrong!Passw0rd"
    #   ACCEPT_EULA: "Y"
    #   ports:
    #      - "1433:1433"
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - 3020:80
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: root@45588522
  #     UPLOAD_LIMIT: 40M       # Set
  #     # MEMORY_LIMIT:400M
  #     # MAX_EXECUTION_TIME
 
volumes:
  db_data: